### ISSUE TITLE
Demo content for the demo site

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/low-carbon-template#18]
## Tasks

- [ ] Homepage: reuse content from Nandini’s designs
- [ ] Blog index: reuse designs
- [x] Blog post 1: sustainability
- [x] Blog post 2: accessibility
- [ ] Blog post 3: SEO
- [ ] Blog post 4: Wagtail
- [x] (image / visuals for 1-2 blog posts)

Demo content document: https://docs.google.com/document/d/18yUAKeU1K45XtRB6ZaVeQmYK9DrSksuErowdS6qKhx8/edit#heading=h.1rwph26e4w76
